# DEBUG_MODE, set to true to enable additional console logging
# Note: this is a boolean value, so it should be set to true or false
debug-mode: false

# SIMPLEX_CHAT_PORT, set the port number to match what you use when starting the simplex-chat command from Terminal
# Note: this is a number value, Simplex Chat recommends 5225
simplex-chat-port: 5225

#################################################################################################
# Note: any specific temperature requests by users will have their own color coding separate
# from the general thresholds below
#################################################################################################

# summerTempHot, temperature threshold during summer months providing color coding on temp reporting
summer-temp-hot: 85

# tempHot, temperature color coding threshold for all non-summer months
temp-hot: 75

# tempCold, temperature color coding threshold for any temperature below this value all year round
temp-cold: 50

# shareBotAddress, Makes the weatherBot profile address shareable, allowing users to share it with others at will
# Note: if you want to control who can connect to weatherBot, set this to false and manually share the address with others
#       - you'll need to do this manually by copying the address displayed on console output when weatherBot starts up
# Note: this is a boolean value, so it should be set to true or false
share-bot-address: true

# initHostUser, optional Simplex user address to use (or reset) the initial host/admin user upon (re)startup
# value needs to be quoted due to Simplex use of special chars
init-host-user:
